CREATE TABLE PERFIL (
    ID VARCHAR(2) PRIMARY KEY,
    DESCRICAO VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE USUARIO (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(150) NOT NULL,
    PERFILID VARCHAR(2) NOT NULL REFERENCES PERFIL(ID),
    EMAIL VARCHAR(150),
    TELEFONE VARCHAR(30),
    SENHAHASH VARCHAR(255) NOT NULL,
    DATACADASTRO TIMESTAMP DEFAULT NOW()
);

CREATE TABLE CLIENTE (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(150) NOT NULL,
    TIPOPESSOA VARCHAR(2) NOT NULL,
    CGC VARCHAR(20) NOT NULL,
    DATANASCIMENTO DATE,
    TELEFONE VARCHAR(30),
    EMAIL VARCHAR(150),
    ENDERECO VARCHAR(255),
    CEP VARCHAR(9),
    DATACADASTRO TIMESTAMP DEFAULT NOW()
);

CREATE TABLE CANAL (
    ID VARCHAR(2) PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE TIPOREF (
    ID VARCHAR(15) PRIMARY KEY,
    DESCRICAO VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE SOLICITACAO (
    ID SERIAL PRIMARY KEY,
    CLIENTEID INT NOT NULL REFERENCES CLIENTE(ID),
    TIPO VARCHAR(20) NOT NULL,
    DESCRICAO TEXT,
    STATUS VARCHAR(20) NOT NULL,
    DATACRIACAO TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE HISTORICO (
    ID SERIAL PRIMARY KEY,
    CLIENTEID INT NOT NULL REFERENCES CLIENTE(ID),
    USUARIOID INT REFERENCES USUARIO(ID),
    CANALID VARCHAR(2) NOT NULL REFERENCES CANAL(ID),
    DATAHORA TIMESTAMP NOT NULL DEFAULT NOW(),
    DESCRICAO TEXT,
    TIPOREF VARCHAR(15) REFERENCES TIPOREF(ID),
    REFERENCIAID INT
);

CREATE TABLE ORCAMENTO (
    ID SERIAL PRIMARY KEY,
    SOLICITACAOID INT NOT NULL REFERENCES SOLICITACAO(ID),
    CLIENTEID INT NOT NULL REFERENCES CLIENTE(ID),
    USUARIOID INT REFERENCES USUARIO(ID),
    DATACRIACAO TIMESTAMP DEFAULT NOW(),
    DATAENVIO TIMESTAMP,
    DATARESPOSTA TIMESTAMP,
    STATUS VARCHAR(20) NOT NULL,
    VALORTOTAL NUMERIC(12,2) DEFAULT 0,
    OBSERVACOES TEXT
);

CREATE TABLE ORCAMENTOIT (
    ID SERIAL PRIMARY KEY,
    ORCAMENTOID INT NOT NULL REFERENCES ORCAMENTO(ID),
    DESCRICAO VARCHAR(255) NOT NULL,
    QUANTIDADE NUMERIC(10,2) DEFAULT 1,
    VALORUNITARIO NUMERIC(12,2) NOT NULL,
    DESCONTO NUMERIC(12,2) DEFAULT 0,
    ACRESCIMO NUMERIC(12,2) DEFAULT 0
);

CREATE TABLE ORDEMSERVICO (
    ID SERIAL PRIMARY KEY,
    ORCAMENTOID INT REFERENCES ORCAMENTO(ID),
    CLIENTEID INT NOT NULL REFERENCES CLIENTE(ID),
    USUARIOID INT REFERENCES USUARIO(ID),
    STATUS VARCHAR(2) NOT NULL,
    DATAPLANEJADA DATE,
    DATACONCLUSAO DATE,
    OBSERVACOES TEXT
);

CREATE TABLE TECNICO (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(150) NOT NULL,
    TELEFONE VARCHAR(30)
);

CREATE TABLE VISITA (
    ID SERIAL PRIMARY KEY,
    ORDEMSERVICOID INT NOT NULL REFERENCES ORDEMSERVICO(ID),
    TECNICOID INT REFERENCES TECNICO(ID),
    DATAAGENDADA TIMESTAMP,
    DATAREALIZADA TIMESTAMP,
    STATUS VARCHAR(2) NOT NULL,
    VALOR NUMERIC(12,2) DEFAULT 0,
    DESCONTO NUMERIC(12,2) DEFAULT 0,
    ACRESCIMO NUMERIC(12,2) DEFAULT 0,
    OBSERVACOES TEXT
);

CREATE TABLE EQUIPAMENTO (
    ID SERIAL PRIMARY KEY,
    CLIENTEID INT NOT NULL REFERENCES CLIENTE(ID),
    ORDEMSERVICOID INT REFERENCES ORDEMSERVICO(ID),
    TIPO VARCHAR(100),
    MARCA VARCHAR(100),
    MODELO VARCHAR(100),
    NUMEROSERIE VARCHAR(100),
    VALOR NUMERIC(12,2) DEFAULT 0,
    DESCONTO NUMERIC(12,2) DEFAULT 0,
    ACRESCIMO NUMERIC(12,2) DEFAULT 0,
    DATAINSTALACAO DATE
);

CREATE TABLE GARANTIA (
    ID SERIAL PRIMARY KEY,
    EQUIPAMENTOID INT NOT NULL REFERENCES EQUIPAMENTO(ID),
    TIPO VARCHAR(20) NOT NULL,
    DATAINICIO DATE NOT NULL,
    DATAFIM DATE NOT NULL,
    STATUS VARCHAR(2) NOT NULL
);

CREATE TABLE GARANTIANOTIF (
    ID SERIAL PRIMARY KEY,
    GARANTIAID INT NOT NULL REFERENCES GARANTIA(ID),
    DATAENVIO TIMESTAMP DEFAULT NOW(),
    ANTECEDENCIADIAS INT,
    STATUS VARCHAR(2) NOT NULL
);

CREATE TABLE ARQUIVO (
    ID SERIAL PRIMARY KEY,
    TIPOREF VARCHAR(15) NOT NULL REFERENCES TIPOREF(ID),
    REFERENCIAID INT NOT NULL,
    NOME VARCHAR(255),
    CAMINHO VARCHAR(500) NOT NULL,
    TIPO VARCHAR(50),
    TAMANHO INT,
    DATAUPLOAD TIMESTAMP DEFAULT NOW()
);

-- TABELAS DE CONTROLE

INSERT INTO PERFIL (ID, DESCRICAO) VALUES
    ('V', 'Vendedor'),
    ('T', 'Técnico'),
    ('A', 'Administrador');

INSERT INTO CANAL (ID, NOME) VALUES
    ('S', 'Site'),
    ('W', 'WhatsApp'),
    ('L', 'Ligação'),
    ('P', 'Presencial'),
    ('E', 'E-mail');

INSERT INTO TIPOREF (ID, DESCRICAO) VALUES
    ('SOL', 'Solicitação'),
    ('ORC', 'Orçamento'),
    ('OS', 'Ordem de serviço'),
    ('GAR', 'Garantia'),
    ('EQP', 'Equipamento');